name: uservices
description: 4uServices freelancer babershop.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  get: ^3.17.1
  get_storage: ^1.0.0
  intl: ^0.16.1
  dio: ^3.0.9
  retrofit: ^1.3.4
  backendless_sdk: ^6.1.0
  json_serializable: ^3.5.0
  progress_dialog: ^1.2.4
  cached_network_image: ^2.3.2
  kf_drawer: ^1.1.2
  image_picker: ^0.6.7+14
  brasil_fields: ^0.6.0
  flutter_datetime_picker: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  retrofit_generator: ^1.3.7

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Black
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf

    - family: Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: ExtraBold
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf

    - family: ExtraLight
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLight.ttf

    - family: Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf

    - family: Thin
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
